const {JSDOM}=require('jsdom');
const fs=require('fs'),assert=require('node:assert/strict');
const root=require('node:path').resolve(__dirname,'..'),base='http://127.0.0.1:5005';
const dom=new JSDOM(fs.readFileSync(root+'/backend/templates/index.html','utf8'),{url:base,runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window;const browser={cookie:'',csrf:''};let failPoll=false;const copied=[];Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async text=>copied.push(text)}});
async function request(client,path,options={}){
 const response=await fetch(base+path,{...options,headers:{...options.headers,...(client.cookie?{Cookie:client.cookie}:{})}});
 const cookie=response.headers.get('set-cookie');if(cookie)client.cookie=cookie.split(';')[0];
 return response;
}
w.fetch=async(path,options={})=>{if(failPoll&&path==='/api/accounts'){failPoll=false;throw Error('Simulated connection loss');}return request(browser,path,options);};
w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};
w.eval(fs.readFileSync(root+'/backend/static/app.js','utf8'));
const find=s=>w.document.querySelector(s),click=s=>{assert(find(s),'Missing '+s);find(s).click();};
const wait=async(fn,label)=>{const end=Date.now()+8000;while(Date.now()<end){if(fn())return;await new Promise(r=>setTimeout(r,25));}throw Error('Timeout: '+label+'; '+find('#login-error')?.textContent);};
async function post(client,path,data,method='POST'){
 if(!client.csrf)client.csrf=(await (await request(client,'/api/session')).json()).csrf;
 const response=await request(client,path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':client.csrf},body:JSON.stringify(data)});
 const result=await response.json();assert(response.ok,JSON.stringify(result));if(result.csrf)client.csrf=result.csrf;if(path==='/api/logout')client.csrf='';return result;
}
(async()=>{
 await wait(()=>!find('#login-screen').hidden,'sign-in');click('[data-auth-mode="demo-signup"]');
 const form=find('#login-form');form.elements.name.value='Campus Admin';form.elements.role.value='admin';form.elements.email.value='admin@example.test';form.elements.password.value=form.elements.confirm_password.value='CampusPassword123!';
 form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>!find('#login-success').hidden,'signup');
 const signupCode=find('#signup-student-code').textContent,signupStaffCode=find('#signup-staff-code').textContent;
 assert(!find('#signup-invites').hidden&&find('#workspace').hidden);assert(signupCode.startsWith('CG-STU-')&&signupStaffCode.startsWith('CG-STF-'));
 click('#signup-invites [data-role=student]');click('#signup-invites [data-role=staff]');await wait(()=>copied.length===2,'copy codes');assert.deepEqual(copied,[signupCode,signupStaffCode]);
 form.elements.password.value='CampusPassword123!';form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await wait(()=>!find('#workspace').hidden&&find('#page-title').textContent==='Overview'&&!find('#auth-submit').disabled,'admin login');
 click('[data-page="accounts"]');await wait(()=>find('#campus-code'),'account directory');
 const code=find('#campus-code').textContent,staffCode=find('#staff-campus-code').textContent;assert.equal(code,signupCode);assert.equal(staffCode,signupStaffCode);assert(find('#signup-invites').hidden);
 const search=find('#accounts-search');search.value='New Student';search.dispatchEvent(new w.Event('input',{bubbles:true}));search.focus();
 const student={cookie:'',csrf:''};const credentials={email:'student@example.test',password:'StudentPassword123!',role:'student',name:'New Student',campus_code:code};
 await post(student,'/api/demo/signup',credentials);
 await wait(()=>find('#accounts-table').textContent.includes('New Student'),'new registration appears without refresh');
 assert.equal(find('#accounts-search'),search);assert.equal(w.document.activeElement,search);assert.equal(search.value,'New Student');
 assert(find('#accounts-table').textContent.includes('Offline'));
 await post(student,'/api/demo/login',credentials);
 await wait(()=>find('#accounts-table').textContent.includes('Online'),'online presence');
 const ownRecord=(await (await request(student,'/api/students')).json()).students[0];
 await post(student,'/api/students/'+ownRecord.student_id,{name:'New Student',department:'Business',year:4,cgpa:9.25,consent:true},'PUT');

 await post(student,'/api/logout',{});
 await wait(()=>find('#accounts-table').textContent.includes('Offline'),'offline presence');
 failPoll=true;
 await wait(()=>find('#live-status').textContent.includes('Connection lost'),'connection failure visible');
 await wait(()=>find('#live-status').textContent.includes('Live'),'automatic reconnection');
 assert.equal(find('#accounts-search').value,'New Student');
 click('[data-page="students"]');await wait(()=>find('#directory-table')?.textContent.includes('New Student'),'enrolled record');
 assert(find('#directory-table').textContent.includes('Awaiting Admin review')&&find('#directory-table').textContent.includes('9.25'));
 await post(student,'/api/demo/login',credentials);await post(student,'/api/students/'+ownRecord.student_id,{cgpa:9.5},'PUT');await wait(()=>find('#directory-table').textContent.includes('9.50'),'student changes appear automatically');
 const button=find('[data-action="edit"][data-id^="REG-"]');assert(button);button.click();
 const record=find('#record-form');record.elements.name.value='Reviewed Student';record.elements.cgpa.value='8.75';record.elements.year.value='3';record.elements.department.value='Electronics';
 const second={cookie:'',csrf:''};await post(second,'/api/demo/signup',{...credentials,email:'second@example.test',name:'Second Student'});
 await new Promise(r=>setTimeout(r,5200));assert(find('#record-dialog').hasAttribute('open'));assert.equal(record.elements.name.value,'Reviewed Student');
 record.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>!find('#record-dialog').hasAttribute('open'),'review saved');
 await wait(()=>find('#directory-table')?.textContent.includes('Reviewed Student')&&find('#nav-count').textContent==='14','record and registration refreshed');
 const staff={cookie:'',csrf:''};const staffCredentials={email:'staff@example.test',password:'StaffPassword123!',role:'staff',name:'Campus Staff',campus_code:staffCode};
 const accountNav=find('[data-page="accounts"]');accountNav.click();await wait(()=>find('#accounts-search'),'accounts return');
 const accountSearch=find('#accounts-search');accountSearch.value='';accountSearch.dispatchEvent(new w.Event('input',{bubbles:true}));
 await post(staff,'/api/demo/signup',staffCredentials);
 await wait(()=>find('#accounts-table').textContent.includes('Campus Staff'),'staff registration appears automatically');
 assert(find('#account-metrics').textContent.includes('Registered staff'));
 click('#signout');await wait(()=>!find('#login-screen').hidden,'logout');assert(find('#workspace').hidden);
 form.elements.email.value=staffCredentials.email;form.elements.password.value=staffCredentials.password;form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await wait(()=>!find('#workspace').hidden&&find('#account-role').textContent==='Staff member'&&!find('#auth-submit').disabled,'joined staff login');
 click('[data-page="students"]');await wait(()=>find('#directory-table')?.textContent.includes('•••'),'staff masking');
 assert(find('[data-page="accounts"]').hidden&&!find('[data-action="join-campus"]'));
 const owner={cookie:'',csrf:''};await post(owner,'/api/demo/login',{email:'admin@example.test',password:'CampusPassword123!'});
 const accountData=await (await request(owner,'/api/accounts')).json();assert.equal(accountData.accounts.length,4);
 assert(accountData.accounts.some(a=>a.email==='staff@example.test'&&a.role==='staff'));
 click('#signout');await wait(()=>!find('#login-screen').hidden,'staff logout');
 console.log('Campus live UI passed: immediate separate codes, correct copy buttons, Student and Staff enrollment, automatic registration updates, preserved search, online/offline presence, reconnection, protected editing, and logout.');
 dom.window.close();
})().catch(e=>{console.error(e);dom.window.close();process.exit(1);});
