const {JSDOM}=require('jsdom');
const fs=require('fs');
const assert=require('node:assert/strict');
const root=require('node:path').resolve(__dirname,'..');
const html=fs.readFileSync(root+'/backend/templates/index.html','utf8');
const js=fs.readFileSync(root+'/backend/static/app.js','utf8');
const dom=new JSDOM(html,{url:'http://127.0.0.1:5005/',runScripts:'outside-only'});
const w=dom.window;let cookie='';
w.fetch=async(path,options={})=>{const r=await fetch(new URL(path,'http://127.0.0.1:5005/'),{...options,headers:{...options.headers,...(cookie?{Cookie:cookie}:{})}});const value=r.headers.get('set-cookie');if(value)cookie=value.split(';')[0];return r;};
w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};
w.eval(js+'; window.__parseCSV=parseCSV;');
const wait=async(fn,label)=>{const until=Date.now()+6000;while(Date.now()<until){if(fn())return;await new Promise(r=>setTimeout(r,20));}throw Error('Timed out: '+label+'; message: '+find('#login-error')?.textContent);};
const click=selector=>{const el=w.document.querySelector(selector);assert(el,'Missing '+selector);el.click();};
const find=selector=>w.document.querySelector(selector);
(async()=>{
 await wait(()=>!find('#login-screen').hidden,'sign-in');
 assert(!find('#demo-entry').hidden);
 click('[data-demo="admin"]');
 await wait(()=>find('#page-body').textContent.includes('Recently updated students'),'overview');
 assert(find('#page-body').textContent.includes('12'));
 click('[data-page="students"]');
 await wait(()=>find('#directory-search'),'directory');
 assert.equal(find('#directory-table tbody').children.length,8);
 find('#directory-search').value='Diya';find('#directory-search').dispatchEvent(new w.Event('input',{bubbles:true}));
 assert.equal(find('#directory-table tbody').children.length,1);
 find('#directory-search').value='';find('#directory-search').dispatchEvent(new w.Event('input',{bubbles:true}));
 click('[data-action="add"]');
 const form=find('#record-form');
 const fields={student_id:'UI-TEST',name:'UI Sample',email:'ui@example.test',department:'Computer Science',year:'2',cgpa:'8.9',status:'Active',retention_date:'2028-06-30'};
 for(const [k,v] of Object.entries(fields))form.elements[k].value=v;
 form.elements.consent.checked=true;
 form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await wait(()=>!find('#record-dialog').hasAttribute('open'),'saved');
 await wait(()=>find('#nav-count').textContent==='13','refreshed');
 find('#directory-search').value='UI-TEST';find('#directory-search').dispatchEvent(new w.Event('input',{bubbles:true}));
 assert(find('#directory-table').textContent.includes('UI Sample'));
 click('[data-action="edit"][data-id="UI-TEST"]');form.elements.cgpa.value='9.1';form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await wait(()=>!find('#record-dialog').hasAttribute('open'),'updated');
 await wait(()=>find('#directory-table').textContent.includes('9.10'),'updated value');
 click('[data-action="archive"][data-id="UI-TEST"]');click('#confirm-archive');
 await wait(()=>find('#nav-count').textContent==='12','archived');
 click('[data-page="archive"]');
 await wait(()=>find('[data-action="restore"][data-id="UI-TEST"]'),'archive list');
 click('[data-action="restore"][data-id="UI-TEST"]');
 await wait(()=>find('#nav-count').textContent==='13','restored');
 click('[data-page="privacy"]');await wait(()=>find('#page-body').textContent.includes('Privacy follow-up'),'privacy');
 click('[data-page="audit"]');await wait(()=>find('#audit-search'),'activity log');
 assert(find('#audit-table').textContent.includes('Student restored'));
 assert.equal(w.__parseCSV('student_id,name,email,department,consent\nCSV-1,"Sample, Name",sample@example.test,Computer Science,true\n')[0].name,'Sample, Name');
 assert.throws(()=>w.__parseCSV('student_id,name,email,department\nA,"Unclosed,x,x'));
 click('#signout');await wait(()=>!find('#login-screen').hidden,'logout');
 click('[data-demo="staff"]');await wait(()=>find('#account-role').textContent==='Staff member'&&!find('#workspace').hidden,'staff demo');
 click('[data-page="students"]');await wait(()=>find('#directory-table')&&find('#directory-table').textContent.includes('•••'),'staff mask');
 assert.equal(find('[data-page="audit"]').hidden,true);
 click('[data-action="edit"]');assert.equal(form.elements.email.disabled,true);
 find('#record-dialog').close();
 click('#signout');await wait(()=>!find('#login-screen').hidden,'staff logout');
 click('[data-demo="student"]');await wait(()=>find('#page-body').textContent.includes('Your student record'),'student demo');
 click('[data-page="students"]');await wait(()=>find('#directory-table tbody'),'student directory');
 assert.equal(find('#directory-table tbody').children.length,1);
 assert.equal(find('[data-action="add"]'),null);
 click('[data-action="edit"]');assert.equal(form.elements.email.disabled,true);assert.equal(form.elements.student_id.disabled,true);assert(form.elements.status.disabled&&form.elements.status.closest('label').hidden);
 form.elements.name.value='Student Submitted';form.elements.department.value='Business';form.elements.year.value='4';form.elements.cgpa.value='9.25';form.elements.consent.checked=true;
 form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>!find('#record-dialog').hasAttribute('open'),'student submitted');
 await wait(()=>find('#directory-table').textContent.includes('Student Submitted')&&find('#directory-table').textContent.includes('9.25')&&find('#directory-table').textContent.includes('Awaiting Admin review'),'student details shown');

 click('#signout');await wait(()=>!find('#login-screen').hidden,'student logout');
 click('[data-auth-mode="demo-signup"]');
 const authForm=find('#login-form');
 authForm.elements.name.value='Walkthrough Admin';authForm.elements.role.value='admin';authForm.elements.confirm_password.value='DemoPassword123!';authForm.elements.email.value='walkthrough@example.test';authForm.elements.password.value='DemoPassword123!';
 authForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await wait(()=>!find('#login-success').hidden && find('#login-success').textContent.includes('Admin account created successfully'),'demo signup');
 const codes={student:find('#signup-student-code').textContent,staff:find('#signup-staff-code').textContent};
 assert(!find('#signup-invites').hidden&&codes.student!==codes.staff);
 assert.equal(authForm.elements.password.value,'');
 assert.equal(find('#auth-submit').textContent,'Sign in');
 assert.equal(find('#login-error').textContent,'');
 authForm.elements.password.value='DemoPassword123!';
 authForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await wait(()=>find('#account-email').textContent==='walkthrough@example.test'&&!find('#workspace').hidden&&find('#page-body').textContent.includes('Recently updated students')&&!find('#auth-submit').disabled,'demo account login');
 click('#signout');await wait(()=>!find('#login-screen').hidden,'demo account logout');
 authForm.elements.email.value='walkthrough@example.test';authForm.elements.password.value='DemoPassword123!';
 authForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await wait(()=>find('#account-email').textContent==='walkthrough@example.test'&&!find('#workspace').hidden&&find('#page-body').textContent.includes('Recently updated students')&&!find('#auth-submit').disabled,'demo account return login');
 click('#signout');await wait(()=>!find('#login-screen').hidden,'admin logout');
 for(const role of ['student','staff']){
  click('[data-auth-mode="demo-signup"]');
  authForm.elements.name.value='Signup '+role;
  authForm.elements.role.value=role;find('[name=role][value="'+role+'"]').dispatchEvent(new w.Event('change',{bubbles:true}));
  assert(find('#auth-submit').textContent.includes(role==='student'?'Student':'Staff'));
  authForm.elements.email.value=role+'-signup@example.test';authForm.elements.password.value='RolePassword123!';authForm.elements.confirm_password.value='Mismatch';
  authForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
  await wait(()=>find('#login-error').textContent==='Passwords do not match','mismatch');
  authForm.elements.campus_code.value=codes[role];assert(authForm.elements.campus_code.required&&!authForm.elements.campus_code.disabled);
  authForm.elements.confirm_password.value='RolePassword123!';
  authForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
  await wait(()=>!find('#login-success').hidden,'role signup');
  assert(find('#login-success').textContent.includes(role==='student'?'Student account':'Staff account'));
  authForm.elements.password.value='RolePassword123!';authForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
  await wait(()=>!find('#workspace').hidden&&find('#account-email').textContent===role+'-signup@example.test'&&!find('#auth-submit').disabled,'role login');
  assert(find('#welcome-strip').textContent.includes('Signup '+role));
  assert(find('[data-page="audit"]').hidden);
  click('[data-page="students"]');await wait(()=>find('#directory-table tbody'),'role directory');
  if(role==='student'){assert.equal(find('#directory-table tbody').children.length,1);assert(!find('[data-action="add"]'));}
  else {assert(find('#directory-table').textContent.includes('•••'));assert(find('[data-action="add"]'));}
  click('#signout');await wait(()=>!find('#login-screen').hidden,'role logout');
 }
 console.log('UI integration passed: overview, search, pagination, add/edit, archive/restore, privacy, activity, logout, staff masking and student restrictions; CSV quote parser.');
 dom.window.close();
})().catch(e=>{console.error(e);dom.window.close();process.exit(1);});
